name: output information
on: workflow_dispatch
jobs:
  info:
    runs-on: Ubuntu-latest  
    steps:
      - name: Output Github context
        run: 
          echo "The repository is ${{ github.repository }}"  
          echo "The repository is ${{ toJSON(github) }}"  
